version: '3'

services:
  avito:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"  
    depends_on:
      - db
    environment:
      DATABASE_DSN: postgresql://postgres:postgres@db/avito?sslmode=disable
      ADDRESS: avito:8080

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5436:5432
    volumes:
      - pqdata:/var/lib/postgresql/data/
      - ./assets/postgres:/docker-entrypoint-initdb.d

volumes:
  pqdata: 